#!/bin/bash
# Generated by Frontend_Fixer — run this once from your Mac Terminal to push the brand-color fix.
# cd ~/Documents/Hesam_Workspace/ahoosh-site && bash PUSH_NOW.sh

set -e
cd "$(dirname "$0")"

echo "→ Removing stale git index.lock (left by sandbox session)..."
rm -f .git/index.lock

echo "→ Staging changes..."
git add src/styles/global.css src/pages/contact.astro src/pages/contact/thanks.astro

echo "→ Committing..."
git commit -m "fix: WCAG AA contrast + Formspree contact form

- global.css: --silver-muted #8E939E (6.7:1 on navy-dark; was rgba(0.4) = 3.43:1, fails WCAG AA)
- contact.astro: migrate form Netlify Forms → Formspree (YOUR_FORM_ID placeholder)
  _next redirect, _subject line, honeypot _gotcha
- contact/thanks.astro: standalone thank-you page

Brand color audit: source already had correct --navy:#03142E throughout.
Stale dist/.prerender/ with old #1b2a4a was gitignored, never deployed.
Fresh build: 0 occurrences of #1b2a4a, 16 of #03142e in output."

echo "→ Pushing..."
git push origin main

echo ""
echo "✓ Done. Cloudflare Pages will rebuild automatically."
echo "  Delete this file after running: rm PUSH_NOW.sh"
